name: myapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 
  shared_preferences: ^2.2.2
    

  
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.2.6
  supabase_flutter: ^2.10.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/icon.png"
  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - lib/assets/images/
  
  
